In [20]:
import pandas as pd

df1 = pd.read_csv('./data/Group2.csv', index_col=0)
df1.drop(['저체중률', '독거노인수'], axis=1, inplace=True)
df1.head()

   자치구  행정동  기초생활수급자인원  노년부양비  고령내국인전체  노령화지수  무료급식소개수
0  종로구  사직동      125.0   27.1   1787.0  208.3      0.0
1  종로구  삼청동       45.0   35.1    596.0  266.4      0.0
2  종로구  부암동      174.0   26.2   1808.0  225.6      0.0
3  종로구  평창동      144.0   27.8   3474.0  192.8      0.0
4  종로구  무악동      206.0   26.7   1476.0  141.0      0.0

In [21]:
df2 = pd.read_csv('./data/group2_score.csv')
df2.drop('자치구', axis=1, inplace=True)
df2.head()

    행정동        점수  순위
0  중곡4동  1.163974   1
1   약수동  1.105766   2
2  을지로동  0.951732   3
3  창신1동  0.803631   4
4  자양4동  0.699262   5

In [22]:
df = pd.merge(df1, df2, on='행정동')
df = df.sort_values('점수', ascending=False)
df.reset_index(drop=True, inplace=True)
df.rename(columns={'고령내국인전체':'고령자수'}, inplace=True)
df

    자치구    행정동  기초생활수급자인원  노년부양비    고령자수  노령화지수  무료급식소개수        점수  순위
0   광진구   중곡4동     1534.0   25.7  5411.0  278.8      0.0  1.163974   1
1    중구    약수동      944.0   35.7  3980.0  284.4      0.0  1.105766   2
2    중구   을지로동      148.0   34.1   454.0  659.2      0.0  0.951732   3
3   종로구   창신1동      501.0   29.8  1176.0  555.1      0.0  0.803631   4
4   광진구   자양4동     1001.0   23.9  3749.0  340.0      0.0  0.699262   5
..  ...    ...        ...    ...     ...    ...      ...       ...  ..
75  성동구    사근동      258.0   12.7  1516.0  264.5      0.0 -0.698415  76
76   중구    중림동      622.0   25.1  2187.0  162.1      2.0 -0.717976  77
77  용산구    효창동      132.0   19.4  1576.0  135.5      0.0 -0.752023  78
78  용산구  원효로1동      388.0   14.9  2049.0  116.6      0.0 -0.796847  79
79   중구    소공동       49.0   11.3   258.0   73.1      0.0 -1.515589  80

[80 rows x 9 columns]

In [24]:
df.to_csv('Group2_final.csv', index=False)